const ENUM_DEPARTMENTS = ['QUANTITATIVE', 'QUALITATIVE'];
const ENUM_IDENTITY_TYPES = ['KTP', 'SIM', 'KTM', 'KTS'];
const ENUM_VENDOR_TYPES = ['INTERNAL', 'EXTERNAL'];

module.exports = { ENUM_DEPARTMENTS, ENUM_IDENTITY_TYPES, ENUM_VENDOR_TYPES };
